import os
from typing import List, Tuple

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation


def write_solution_step(
    output_filename: str,
    variable_names: List[str],
    grid: np.ndarray,
    W: np.ndarray,
    t: float,
):
    """
    Saves the current solution state to the output file.

    Args:
        U (np.ndarray): The conservative variables for the main domain.
        t (float): The current simulation time.
        step (int): The current iteration number.
    """
    write_header = (
        not os.path.exists(output_filename) or os.path.getsize(output_filename) == 0
    )
    xmid = (grid[1:] + grid[:-1]) / 2
    mode = "a" if not write_header else "w"
    with open(output_filename, mode) as f:
        if write_header:
            f.write("# variables: " + ", ".join(variable_names) + "\n")
            f.write("# grid: " + " ".join(f"{x:.8g}" for x in xmid) + "\n")
        f.write(f"t={t:.8f}\n")
        if W.shape[0] == len(variable_names):
            W = W.T  # shape: (num_cells, num_vars)
        for row in W:
            f.write(" ".join(f"{val:.8g}" for val in row) + "\n")


def read_solution(
    filename: str,
) -> Tuple[List[str], List, List, np.ndarray]:
    """
    Reads and parses a solution data file generated by the solver, extracting
    variable names and time-step data.

    The file is expected to have a header line for variable names (e.g.,
    '# x, density, ...') and data blocks for each time step. Each block may
    also contain a header for the time step (e.g., '# Step 1, Time 0.0123').

    Args:
        filename (str): The path to the solution data file.

    Returns:
        Tuple[List[str], List[Tuple[float, np.ndarray, np.ndarray]]]:
            A tuple containing:
            - A list of variable names (e.g., ['x', 'density', 'velocity']).
            - A list of tuples for each time step, where each tuple contains
              (time, x_coordinates, W_solution). W_solution has a shape of
              (num_vars, num_cells).
    """
    variable_names = []
    grid = None
    times = []
    solutions = []
    try:
        with open(filename, "r") as f:
            lines = [line.strip() for line in f if line.strip()]
    except FileNotFoundError:
        print(f"Error: Solution file not found at {filename}")
        return [], None, [], []

    i = 0
    while i < len(lines):
        if lines[i].startswith("# variables:"):
            variable_names = [v.strip() for v in lines[i][12:].split(",")]
            i += 1
        elif lines[i].startswith("# grid:"):
            grid = np.array([float(x) for x in lines[i][7:].split()])
            i += 1
        else:
            break
    while i < len(lines):
        if lines[i].startswith("t="):
            t = float(lines[i][2:])
            i += 1
            data_rows = []
            while i < len(lines) and not lines[i].startswith("t="):
                data_rows.append([float(x) for x in lines[i].split()])
                i += 1
            arr = np.array(data_rows)
            solutions.append(arr.T)
            times.append(t)
        else:
            i += 1
    return variable_names, grid, times, solutions


def animate_solution(variable_names, grid, times, solutions, interval=100):
    # Setup figure and lines
    fig, ax = plt.subplots()
    lines = []
    for i, var in enumerate(variable_names):
        (line,) = ax.plot(grid, solutions[0][i, :], label=var)
        lines.append(line)
    ax.set_xlabel("x")
    ax.set_ylabel("Variables")
    # Use ax.set_title instead of ax.text for the title
    ax.set_title(f"Solution at t = {times[0]:.6f}")
    ax.legend()
    ax.grid(True)

    def update(frame):
        for i, line in enumerate(lines):
            line.set_ydata(solutions[frame][i, :])
        ax.set_title(f"Solution at t = {times[frame]:.6f}")
        return lines

    ani = animation.FuncAnimation(
        fig,
        update,
        frames=len(solutions),
        interval=interval,
        blit=False,
        repeat=True,
        repeat_delay=3000,
    )
    plt.show()
